name: Java CI with Gradle
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'zulu'
    - name: Set execute permission
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: "*/build/libs/*.jar"